### ISSUE TITLE
JCE editor

### ISSUE THREAD

**Issue by Pinkeltje** [pixelstunde/joomla-plg-pxlcompressor#1]
Would be great if this could be added to JCE editor image upload as well.

**Comment by pixelstunde** [comment]
@Pinkeltje I continued development of the plugin recently and I will take a look at it soon.

**Comment by Pinkeltje** [comment]
Thx!

**Comment by pixelstunde** [comment]
Thanks to the support of @ryandemmer, uploads in JCE are working now. Update will follow later this week.

**Comment by pixelstunde** [comment]
Added in [Version 1.2](https://github.com/pixelstunde/joomla-plg-pxlcompressor/releases/tag/1.2)
