### ISSUE TITLE
Safe Upload Names issue

### ISSUE THREAD

**Issue by ghost** [pixelstunde/joomla-plg-pxlcompressor#15]
Safe Upload Names issue

we need č to be changed to c is it posible?

**Comment by ghost** [comment]
please inform if pxlcompressor is still under development thank you

**Comment by ghost** [comment]
Christian do you know how to remove alphanumeric characters ?

**Comment by johanpeters** [comment]
see latest post about development

**Comment by pixelstunde** [comment]
Will be working in upcoming release.
