### ISSUE TITLE
scale fill option change fill color

### ISSUE THREAD

**Issue by johanpeters** [pixelstunde/joomla-plg-pxlcompressor#16]
Hello,
i would like to use the scale_fill option so that all images are correctly scaled and borders are filled.
this will result in al images the correct same size.. 
but i would like to know how to change the black color .. if possible make it transparant and not black.

**Comment by pixelstunde** [comment]
Option added in upcoming release

**Comment by johanpeters** [comment]
hello Christian.. i just tested version 1.4.. nice work.. 
but can you add rgba and not RGB .. so filled spaces can have transparancy.. 
creat to see that you working on this extension.
