### ISSUE TITLE
Feature request: saved images

### ISSUE THREAD

**Issue by johanpeters** [pixelstunde/joomla-plg-pxlcompressor#3]
Hello.. thanks for this plugin.. came from EIR.. but this one works greate.. and support JCE Editor.. 
what i would like to see.. 
save original image: currently it saves the images with no compression but with the default resolution.. create, but i would like to save the original image also (image as uploaded).. perhaps in a special folder (images_upload_archive).

**Comment by pixelstunde** [comment]
Sorry, this is clearly a bug I need to take care of. The original images should not have been resized.

**Comment by pixelstunde** [comment]
@johanpeters Sorry for replying that late, but I had no spare time to offer until today.

Sadly I can't reproduce this bug. Can you please add a screenshot of your settings?

**Comment by johanpeters** [comment]
![Schermafbeelding 2019-10-29 om 15 44 06](https://user-images.githubusercontent.com/1411354/67778598-b365a480-fa63-11e9-943e-e15c81c5b73a.png)

**Comment by johanpeters** [comment]
this issues is solved in the latest version ..
