### ISSUE TITLE
filename formats

### ISSUE THREAD

**Issue by johanpeters** [pixelstunde/joomla-plg-pxlcompressor#4]
add a feature to arrange the filename format.
currently it uses the original name+name as configured in the plugin.
it would be handy to have filename customize options.. 
for instants (date_filename_size).. deferent options to configure.
for websites with a lot of images its a struggle to scroll / manage large amount of images.
perhaps auto create subfolder by upload date and then filename (default, custom, default+custom, etc).. 
currently i advice my clients to use date as first part of the name so the images are sorted.
(year+moth+day_filename).. the plugin adds the size.. 
example 20190628_mountain1.jpg).. with plugin its 20190628_mountain1300x400.jpg).
it would be create that the plugin auto ad a - or _  or to be configured caracter between filename and size (or what is configured in the plugin).

**Comment by pixelstunde** [comment]
Makes sense, I will take a look at this soon. 

I guess, I will add an option to imitate the behavior of the WordPress media plugin (upload path images/year/month/image.png) as well as another option with upload date in filename.

**Comment by pixelstunde** [comment]
Added in version 1.3
