### ISSUE TITLE
timestamp to filename

### ISSUE THREAD

**Issue by johanpeters** [pixelstunde/joomla-plg-pxlcompressor#9]
the timestamp add option to the filename does not work for me.. 
setting is not working...

**Comment by pixelstunde** [comment]
It is working fine, please provide more information (haven't tried in JCE yet)

**Comment by johanpeters** [comment]
with default tinyMCE editor it works.. 
upload in joomla media manager works
upload with JCE Editor does not work.. images get uploaded and compressed but no timestamp is added to the image file name..

**Comment by pixelstunde** [comment]
This problem was (probably) produced by JCE overriding the paths, fixed by a workaround function moving file after saving in 1.4
